trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

- script: |
    cd app
    npm ci
  displayName: 'Install dependencies'

- script: |
    cd app
    npm start &
    sleep 5
    curl http://localhost:8080
  displayName: 'Run application test'

- script: |
    cd app
    docker build -t devopsdemoacr2026.azurecr.io/hello-world-app:$(Build.BuildId) .
  displayName: 'Build Docker image'

- task: Docker@2
  displayName: 'Push Docker image to ACR'
  inputs:
    containerRegistry: 'ACR-Docker-Connection'
    repository: 'hello-world-app'
    command: 'push'
    tags: |
      $(Build.BuildId)